services:
  db:
    image: postgres:alpine3.18
    container_name: ${POSTGRES_HOSTNAME}
    hostname: ${POSTGRES_HOSTNAME}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

  wait-for-db:
    image: atkrad/wait4x
    depends_on:
      - db
    command: tcp ${POSTGRES_HOSTNAME}:${POSTGRES_PORT} -t 30s -i 250ms

  rabbit:
    image: rabbitmq:3-management
    container_name: ${RABBIT_HOSTNAME}
    hostname: ${RABBIT_HOSTNAME}
    ports:
      - 5672:5672
      - 15672:15672

  nats:
    image: nats
    container_name: ${NATS_HOSTNAME}
    hostname: ${NATS_HOSTNAME}
    ports:
      - 4222:4222

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}
    hostname: ${APP_NAME}
    restart: always
    ports:
      - ${RUNNING_PORT}:${RUNNING_PORT}
    depends_on:
      wait-for-db:
        condition: service_completed_successfully
    links:
      - db
